### ISSUE TITLE
Odd failure with file renames

### ISSUE THREAD

**Issue by kghosesbg** [sbg/sevenbridges-python#32]
This code always fails for me. I tried it with three different files in this project. I can change the name fine via the UI. Thanks!

```
import os
import sevenbridges as sbg

api = sbg.Api(url=os.environ['SBG_API_URL'], token=os.environ['SBG_AUTH_TOKEN'])
f = api.files.get(id='57c3337de4b06ea683b426bd')
# f = api.files.get(id='57c3337de4b06ea683b426bf')
# f = api.files.get(id='57c3337de4b06ea683b426bb')
print(f.name)

f.name = 'this.txt'
f.save()
print(f.name)
```

Output:

```
f2.txt
Traceback (most recent call last):
  File "file_save_api_bug.py", line 11, in <module>
    f.save()
  File "/Users/kghose/miniconda2/envs/bench/lib/python2.7/site-packages/sevenbridges/decorators.py", line 23, in wrapped
    api_object = method(obj, *args, **kwargs)
  File "/Users/kghose/miniconda2/envs/bench/lib/python2.7/site-packages/sevenbridges/models/file.py", line 204, in save
    url=self._URL['get'].format(id=self.id), data=modified_data
  File "/Users/kghose/miniconda2/envs/bench/lib/python2.7/site-packages/sevenbridges/http/client.py", line 170, in patch
    data=data, append_base=append_base)
  File "/Users/kghose/miniconda2/envs/bench/lib/python2.7/site-packages/sevenbridges/decorators.py", line 100, in wrapper
    raise SbgError(message=str(e))
sevenbridges.errors.SbgError: No JSON object could be decoded
```

**Comment by kghosesbg** [comment]
@SenadI This could be a API issue though. Let's wait on this.
